Algoritmo "CalculoIdade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/10/2023
Var
// Seção de Declarações das variáveis 
    ano: inteiro

Inicio
 Escreva("Em que ano estamos? ")
 Leia(ano)
 Escreval("Estamos no ano de ", ano)
 Se (ano <= 2023) entao
   Escreva ("Ainda sou novo! ")
 senao(ano > 2023)
   Escreva ("Putz estou velho! ")
 FimSe
 


Fimalgoritmo
